// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: social.craftsky.actor.profile

package craftsky

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("social.craftsky.actor.profile", &ActorProfile{})
}

type ActorProfile struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=social.craftsky.actor.profile"`
	// crafts: The crafts this user practices. Free-form but clients may normalize against the craftType tokens defined in social.craftsky.feed.defs (knitting, crochet, sewing, embroidery, quilting, etc.).
	Crafts []string `json:"crafts,omitempty" cborgen:"crafts,omitempty"`
}
