// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: social.craftsky.business.defs

package craftsky

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// BusinessDefs_Action is a "action" in the social.craftsky.business.defs schema.
//
// The declaration's primary external action.
type BusinessDefs_Action struct {
	// destination: External web or email destination selected by the author.
	Destination string `json:"destination" cborgen:"destination"`
	// type: Open action type; clients apply behavior only to values they recognize.
	Type string `json:"type" cborgen:"type"`
}

// BusinessDefs_AspectRatio is a "aspectRatio" in the social.craftsky.business.defs schema.
//
// Image aspect ratio metadata used for layout hints.
type BusinessDefs_AspectRatio struct {
	Height int64 `json:"height" cborgen:"height"`
	Width  int64 `json:"width" cborgen:"width"`
}

// BusinessDefs_Image is a "image" in the social.craftsky.business.defs schema.
//
// A business product or event image with optional accessibility and layout metadata.
type BusinessDefs_Image struct {
	// alt: Optional alt text describing the image.
	Alt *string `json:"alt,omitempty" cborgen:"alt,omitempty"`
	// aspectRatio: Optional aspect ratio metadata for rendering.
	AspectRatio *BusinessDefs_AspectRatio `json:"aspectRatio,omitempty" cborgen:"aspectRatio,omitempty"`
	Image       *lexutil.LexBlob          `json:"image" cborgen:"image"`
}

// BusinessDefs_Price is a "price" in the social.craftsky.business.defs schema.
//
// Seller-authored display price amount and ISO 4217 currency code.
type BusinessDefs_Price struct {
	// amount: Nonnegative decimal amount interpreted according to the currency minor-unit scale.
	Amount string `json:"amount" cborgen:"amount"`
	// currency: Uppercase ISO 4217 alphabetic currency code.
	Currency string `json:"currency" cborgen:"currency"`
}

// BusinessDefs_Product is a "product" in the social.craftsky.business.defs schema.
//
// An external product card in authored display order.
type BusinessDefs_Product struct {
	// image: Optional product image for interoperable records; Craftsky writes require it.
	Image *BusinessDefs_Image `json:"image,omitempty" cborgen:"image,omitempty"`
	// price: Optional seller-authored display price.
	Price *BusinessDefs_Price `json:"price,omitempty" cborgen:"price,omitempty"`
	// title: Seller-authored product title.
	Title string `json:"title" cborgen:"title"`
	// uri: External product destination.
	Uri string `json:"uri" cborgen:"uri"`
}
