// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: social.craftsky.business.profile

package craftsky

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
	communitylexicon "social.craftsky/appview/internal/lexicon/community"
)

func init() {
	lexutil.RegisterType("social.craftsky.business.profile", &BusinessProfile{})
}

type BusinessProfile struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=social.craftsky.business.profile"`
	// businessTypes: Open, unordered business-type values.
	BusinessTypes []string `json:"businessTypes,omitempty" cborgen:"businessTypes,omitempty"`
	// hoursNote: Display-only free-text hours note.
	HoursNote *string `json:"hoursNote,omitempty" cborgen:"hoursNote,omitempty"`
	// location: General business location using the CID-pinned community address definition.
	Location *communitylexicon.LocationAddress `json:"location,omitempty" cborgen:"location,omitempty"`
	// offerings: Open, unordered offering values.
	Offerings []string `json:"offerings,omitempty" cborgen:"offerings,omitempty"`
	// primaryAction: Optional primary external action.
	PrimaryAction *BusinessDefs_Action `json:"primaryAction,omitempty" cborgen:"primaryAction,omitempty"`
	// products: Featured external products in authored order.
	Products []*BusinessDefs_Product `json:"products,omitempty" cborgen:"products,omitempty"`
	// serviceArea: Display-only uninterpreted service-area text.
	ServiceArea *string `json:"serviceArea,omitempty" cborgen:"serviceArea,omitempty"`
	// tagline: Short public business description.
	Tagline *string `json:"tagline,omitempty" cborgen:"tagline,omitempty"`
}
