// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: social.craftsky.business.event

package craftsky

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("social.craftsky.business.event", &BusinessEvent{})
}

type BusinessEvent struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=social.craftsky.business.event"`
	// createdAt: Record creation timestamp. Craftsky server-stamps and preserves this value.
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	// endsAt: Exclusive event end instant for all-day events and end instant otherwise.
	EndsAt string `json:"endsAt" cborgen:"endsAt"`
	// eventUri: Optional external event information destination.
	EventUri *string `json:"eventUri,omitempty" cborgen:"eventUri,omitempty"`
	// image: Optional event image.
	Image *BusinessDefs_Image `json:"image,omitempty" cborgen:"image,omitempty"`
	// isAllDay: True when start and exclusive end represent local-midnight all-day boundaries; omitted means false.
	IsAllDay *bool `json:"isAllDay,omitempty" cborgen:"isAllDay,omitempty"`
	// mode: Open event attendance mode.
	Mode *string `json:"mode,omitempty" cborgen:"mode,omitempty"`
	// name: Public event name.
	Name string `json:"name" cborgen:"name"`
	// registrationUri: Optional external registration destination.
	RegistrationUri *string `json:"registrationUri,omitempty" cborgen:"registrationUri,omitempty"`
	// roles: Open set of the business's roles at the event.
	Roles []string `json:"roles" cborgen:"roles"`
	// startsAt: Inclusive event start instant.
	StartsAt string `json:"startsAt" cborgen:"startsAt"`
	// status: Open authored lifecycle status; completion is derived from endsAt.
	Status *string `json:"status,omitempty" cborgen:"status,omitempty"`
	// summary: Optional summary of the business's public appearance.
	Summary *string `json:"summary,omitempty" cborgen:"summary,omitempty"`
	// timeZone: IANA timezone name used to interpret all-day boundaries.
	TimeZone *string `json:"timeZone,omitempty" cborgen:"timeZone,omitempty"`
	// venueName: Optional display-only venue name.
	VenueName *string `json:"venueName,omitempty" cborgen:"venueName,omitempty"`
}
