// Package craftsky holds Go types generated from the
// social.craftsky.* lexicon JSON schemas under //lexicon/social/craftsky.
//
// All .go files in this package are generated by `just lexgen` (which
// chains indigo's cmd/lexgen with whyrusleeping/cbor-gen). Do not edit
// them by hand — changes are overwritten on the next regeneration.
//
// Toolchain and conventions are documented in
// docs/superpowers/specs/2026-04-26-lexicon-codegen-design.md.
package craftsky
