// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: social.craftsky.feed.post

package craftsky

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"

	comatproto "github.com/bluesky-social/indigo/api/atproto"
	appbsky "github.com/bluesky-social/indigo/api/bsky"
	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
)

func init() {
	lexutil.RegisterType("social.craftsky.feed.post", &FeedPost{})
}

type FeedPost struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=social.craftsky.feed.post"`
	// createdAt: Client-declared creation timestamp.
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	// embed: Optional embedded content. Open union; today only quote embeds are defined.
	Embed *FeedPost_Embed `json:"embed,omitempty" cborgen:"embed,omitempty"`
	// facets: Byte-range annotations over 'text' for mentions, links, and inline hashtags. Reuses app.bsky.richtext.facet so existing renderers Just Work. Inline hashtag facets are composer-merged into project.common.tags on project posts; see the post lexicon fields spec.
	Facets []*appbsky.RichtextFacet `json:"facets,omitempty" cborgen:"facets,omitempty"`
	// images: Images attached to the post. Top-level (not inside 'embed') — a post may carry images alongside a quote embed without needing a wrapper variant.
	Images []*FeedPost_Image `json:"images,omitempty" cborgen:"images,omitempty"`
	// langs: Indicates human language of post primary text content.
	Langs []string `json:"langs,omitempty" cborgen:"langs,omitempty"`
	// project: If present, this post is a craft project post. Absence means it's a general social post.
	Project *FeedPost_Project `json:"project,omitempty" cborgen:"project,omitempty"`
	// reply: If present, this post is a reply to another post.
	Reply *FeedPost_ReplyRef `json:"reply,omitempty" cborgen:"reply,omitempty"`
	// text: The primary text content of the post. Plain text; rich-text annotations live in 'facets'. Craftsky allows longer posts than Bluesky (2000 graphemes vs 300) because crafters write fuller project write-ups.
	Text string `json:"text" cborgen:"text"`
}

// Optional embedded content. Open union; today only quote embeds are defined.
type FeedPost_Embed struct {
	FeedPost_QuoteEmbed *FeedPost_QuoteEmbed
}

func (t *FeedPost_Embed) MarshalJSON() ([]byte, error) {
	if t.FeedPost_QuoteEmbed != nil {
		t.FeedPost_QuoteEmbed.LexiconTypeID = "social.craftsky.feed.post#quoteEmbed"
		return json.Marshal(t.FeedPost_QuoteEmbed)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *FeedPost_Embed) UnmarshalJSON(b []byte) error {
	typ, err := lexutil.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "social.craftsky.feed.post#quoteEmbed":
		t.FeedPost_QuoteEmbed = new(FeedPost_QuoteEmbed)
		return json.Unmarshal(b, t.FeedPost_QuoteEmbed)
	default:
		return nil
	}
}

func (t *FeedPost_Embed) MarshalCBOR(w io.Writer) error {

	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if t.FeedPost_QuoteEmbed != nil {
		return t.FeedPost_QuoteEmbed.MarshalCBOR(w)
	}
	return fmt.Errorf("can not marshal empty union as CBOR")
}

func (t *FeedPost_Embed) UnmarshalCBOR(r io.Reader) error {
	typ, b, err := lexutil.CborTypeExtractReader(r)
	if err != nil {
		return err
	}

	switch typ {
	case "social.craftsky.feed.post#quoteEmbed":
		t.FeedPost_QuoteEmbed = new(FeedPost_QuoteEmbed)
		return t.FeedPost_QuoteEmbed.UnmarshalCBOR(bytes.NewReader(b))
	default:
		return nil
	}
}

// FeedPost_Image is a "image" in the social.craftsky.feed.post schema.
//
// An image blob with alt text.
type FeedPost_Image struct {
	// alt: Alt text describing the image for accessibility.
	Alt   string           `json:"alt" cborgen:"alt"`
	Image *lexutil.LexBlob `json:"image" cborgen:"image"`
}

// FeedPost_Pattern is a "pattern" in the social.craftsky.feed.post schema.
//
// Optional reference to the pattern used. Every field optional — 'Simplicity 8265' (name only), 'https://ravelry.com/patterns/library/hitchhiker' (URL only), or both plus difficulty are all valid.
type FeedPost_Pattern struct {
	// difficulty: Pattern difficulty as rated by the designer. A property of the pattern, not the post — self-drafted or free-formed projects should leave this empty. knownValues are tokens.
	Difficulty *string `json:"difficulty,omitempty" cborgen:"difficulty,omitempty"`
	// name: Pattern name, e.g. 'Simplicity 8265' or 'Hitchhiker Shawl'. Useful when there is no URL (e.g. a physical pattern), or alongside a URL as a display label.
	Name *string `json:"name,omitempty" cborgen:"name,omitempty"`
	// url: Link to the pattern.
	Url *string `json:"url,omitempty" cborgen:"url,omitempty"`
}

// FeedPost_Project is a "project" in the social.craftsky.feed.post schema.
//
// Wraps a craft project's shared fields (#projectCommon) and optional craft-specific fields (#details, open union). The wrapper exists so shared fields live in one place (common) while per-craft specialisations are added additively via the union. See ADR 001.
type FeedPost_Project struct {
	// common: Shared project fields that apply across all crafts.
	Common *FeedPost_ProjectCommon `json:"common" cborgen:"common"`
	// details: Optional craft-specific fields. Open union — new crafts add new variants here without breaking existing records.
	Details *FeedPost_Project_Details `json:"details,omitempty" cborgen:"details,omitempty"`
}

// FeedPost_ProjectCommon is a "projectCommon" in the social.craftsky.feed.post schema.
//
// Project fields shared across every craft. A post with project.common present but no project.details is a valid craft-tagged project post without specialised fields — useful when craftType references a craft that has no #details lexicon yet.
type FeedPost_ProjectCommon struct {
	// craftType: The craft this project belongs to. Required — a project post without a craft type is meaningless. knownValues are tokens; new crafts can be added to feed.defs without breaking old clients.
	CraftType string `json:"craftType" cborgen:"craftType"`
	// duration: Free-text description of how long the project took, e.g. '3 weeks', 'a weekend', '6 months of evenings'. Deliberately unstructured — crafters describe duration informally. Not range-queryable.
	Duration *string `json:"duration,omitempty" cborgen:"duration,omitempty"`
	// materials: Materials used in the project, as free-form tags. Indexed for search, e.g. 'show me all projects using linen'. Structure per material is intentionally free-form because every craft uses different material descriptors.
	Materials []string `json:"materials,omitempty" cborgen:"materials,omitempty"`
	// pattern: Optional pattern reference.
	Pattern *FeedPost_Pattern `json:"pattern,omitempty" cborgen:"pattern,omitempty"`
	// status: Whether the project is in progress or finished at the time this post was created. Snapshot — not a mutable lifecycle flag. knownValues are tokens so new statuses (e.g. planned, frogged) can be added without breaking old clients.
	Status *string `json:"status,omitempty" cborgen:"status,omitempty"`
	// tags: Structured search tags. Composer responsibility to normalise to ASCII kebab-case (pattern ^[a-z0-9]+(-[a-z0-9]+)*$) and to merge any inline #hashtag facets from text into this field. AppView indexer materialises this as a multi-value searchable column.
	Tags []string `json:"tags,omitempty" cborgen:"tags,omitempty"`
	// title: Optional project name, e.g. 'Hitchhiker Shawl' or 'Linen Summer Dress'. Clients showing grid/card views should fall back to truncated text when title is absent.
	Title *string `json:"title,omitempty" cborgen:"title,omitempty"`
}

// Optional craft-specific fields. Open union — new crafts add new variants here without breaking existing records.
type FeedPost_Project_Details struct {
	ProjectSewing_Details *ProjectSewing_Details
}

func (t *FeedPost_Project_Details) MarshalJSON() ([]byte, error) {
	if t.ProjectSewing_Details != nil {
		t.ProjectSewing_Details.LexiconTypeID = "social.craftsky.project.sewing#details"
		return json.Marshal(t.ProjectSewing_Details)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *FeedPost_Project_Details) UnmarshalJSON(b []byte) error {
	typ, err := lexutil.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "social.craftsky.project.sewing#details":
		t.ProjectSewing_Details = new(ProjectSewing_Details)
		return json.Unmarshal(b, t.ProjectSewing_Details)
	default:
		return nil
	}
}

func (t *FeedPost_Project_Details) MarshalCBOR(w io.Writer) error {

	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if t.ProjectSewing_Details != nil {
		return t.ProjectSewing_Details.MarshalCBOR(w)
	}
	return fmt.Errorf("can not marshal empty union as CBOR")
}

func (t *FeedPost_Project_Details) UnmarshalCBOR(r io.Reader) error {
	typ, b, err := lexutil.CborTypeExtractReader(r)
	if err != nil {
		return err
	}

	switch typ {
	case "social.craftsky.project.sewing#details":
		t.ProjectSewing_Details = new(ProjectSewing_Details)
		return t.ProjectSewing_Details.UnmarshalCBOR(bytes.NewReader(b))
	default:
		return nil
	}
}

// FeedPost_QuoteEmbed is a "quoteEmbed" in the social.craftsky.feed.post schema.
//
// Embed wrapping another record (typically a social.craftsky.feed.post) for a quote post.
type FeedPost_QuoteEmbed struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=social.craftsky.feed.post#quoteEmbed"`
	// record: Strong reference to the quoted record.
	Record *comatproto.RepoStrongRef `json:"record" cborgen:"record"`
}

// FeedPost_ReplyRef is a "replyRef" in the social.craftsky.feed.post schema.
//
// Reference to the parent and root posts of a thread.
type FeedPost_ReplyRef struct {
	// parent: The immediate parent post being replied to.
	Parent *comatproto.RepoStrongRef `json:"parent" cborgen:"parent"`
	// root: The root post of the thread.
	Root *comatproto.RepoStrongRef `json:"root" cborgen:"root"`
}
