// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: social.craftsky.feed.repost

package craftsky

import (
	comatproto "github.com/bluesky-social/indigo/api/atproto"
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("social.craftsky.feed.repost", &FeedRepost{})
}

type FeedRepost struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=social.craftsky.feed.repost"`
	// createdAt: Client-declared creation timestamp of the repost.
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	// subject: Strong reference to the post being reposted.
	Subject *comatproto.RepoStrongRef `json:"subject" cborgen:"subject"`
}
