// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: social.craftsky.feed.post

package craftsky

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"

	comatproto "github.com/bluesky-social/indigo/api/atproto"
	appbsky "github.com/bluesky-social/indigo/api/bsky"
	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
)

func init() {
	lexutil.RegisterType("social.craftsky.feed.post", &FeedPost{})
}

type FeedPost struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=social.craftsky.feed.post"`
	// createdAt: Client-declared creation timestamp.
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	// embed: Optional embedded content. Open union; today only quote embeds are defined.
	Embed *FeedPost_Embed `json:"embed,omitempty" cborgen:"embed,omitempty"`
	// facets: Byte-range annotations over 'text' for mentions, links, and inline hashtags. Reuses app.bsky.richtext.facet so existing renderers Just Work. Inline hashtag facets are composer-merged into project.common.tags on project posts; see the post lexicon fields spec.
	Facets []*appbsky.RichtextFacet `json:"facets,omitempty" cborgen:"facets,omitempty"`
	// images: Images attached to the post. Top-level (not inside 'embed') — a post may carry images alongside a quote embed without needing a wrapper variant.
	Images []*FeedPost_Image `json:"images,omitempty" cborgen:"images,omitempty"`
	// langs: Indicates human language of post primary text content.
	Langs []string `json:"langs,omitempty" cborgen:"langs,omitempty"`
	// project: If present, this post is a craft project post. Absence means it's a general social post.
	Project *ProjectDefs_Project `json:"project,omitempty" cborgen:"project,omitempty"`
	// reply: If present, this post is a reply to another post.
	Reply *FeedPost_ReplyRef `json:"reply,omitempty" cborgen:"reply,omitempty"`
	// text: The primary text content of the post. Plain text; rich-text annotations live in 'facets'. Craftsky allows longer posts than Bluesky (2000 graphemes vs 300) because crafters write fuller project write-ups.
	Text string `json:"text" cborgen:"text"`
}

// FeedPost_AspectRatio is a "aspectRatio" in the social.craftsky.feed.post schema.
//
// Image aspect ratio metadata used for layout/render hints.
type FeedPost_AspectRatio struct {
	Height int64 `json:"height" cborgen:"height"`
	Width  int64 `json:"width" cborgen:"width"`
}

// Optional embedded content. Open union; today only quote embeds are defined.
type FeedPost_Embed struct {
	FeedPost_QuoteEmbed *FeedPost_QuoteEmbed
}

func (t *FeedPost_Embed) MarshalJSON() ([]byte, error) {
	if t.FeedPost_QuoteEmbed != nil {
		t.FeedPost_QuoteEmbed.LexiconTypeID = "social.craftsky.feed.post#quoteEmbed"
		return json.Marshal(t.FeedPost_QuoteEmbed)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *FeedPost_Embed) UnmarshalJSON(b []byte) error {
	typ, err := lexutil.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "social.craftsky.feed.post#quoteEmbed":
		t.FeedPost_QuoteEmbed = new(FeedPost_QuoteEmbed)
		return json.Unmarshal(b, t.FeedPost_QuoteEmbed)
	default:
		return nil
	}
}

func (t *FeedPost_Embed) MarshalCBOR(w io.Writer) error {

	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if t.FeedPost_QuoteEmbed != nil {
		return t.FeedPost_QuoteEmbed.MarshalCBOR(w)
	}
	return fmt.Errorf("can not marshal empty union as CBOR")
}

func (t *FeedPost_Embed) UnmarshalCBOR(r io.Reader) error {
	typ, b, err := lexutil.CborTypeExtractReader(r)
	if err != nil {
		return err
	}

	switch typ {
	case "social.craftsky.feed.post#quoteEmbed":
		t.FeedPost_QuoteEmbed = new(FeedPost_QuoteEmbed)
		return t.FeedPost_QuoteEmbed.UnmarshalCBOR(bytes.NewReader(b))
	default:
		return nil
	}
}

// FeedPost_Image is a "image" in the social.craftsky.feed.post schema.
//
// An image blob with optional alt text.
type FeedPost_Image struct {
	// alt: Optional alt text describing the image for accessibility.
	Alt *string `json:"alt,omitempty" cborgen:"alt,omitempty"`
	// aspectRatio: Optional aspect ratio metadata for rendering.
	AspectRatio *FeedPost_AspectRatio `json:"aspectRatio,omitempty" cborgen:"aspectRatio,omitempty"`
	Image       *lexutil.LexBlob      `json:"image" cborgen:"image"`
}

// FeedPost_QuoteEmbed is a "quoteEmbed" in the social.craftsky.feed.post schema.
//
// Embed wrapping another record (typically a social.craftsky.feed.post) for a quote post.
type FeedPost_QuoteEmbed struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=social.craftsky.feed.post#quoteEmbed"`
	// record: Strong reference to the quoted record.
	Record *comatproto.RepoStrongRef `json:"record" cborgen:"record"`
}

// FeedPost_ReplyRef is a "replyRef" in the social.craftsky.feed.post schema.
//
// Reference to the parent and root posts of a thread.
type FeedPost_ReplyRef struct {
	// parent: The immediate parent post being replied to.
	Parent *comatproto.RepoStrongRef `json:"parent" cborgen:"parent"`
	// root: The root post of the thread.
	Root *comatproto.RepoStrongRef `json:"root" cborgen:"root"`
}
