// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: social.craftsky.feed.like

package craftsky

import (
	comatproto "github.com/bluesky-social/indigo/api/atproto"
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("social.craftsky.feed.like", &FeedLike{})
}

type FeedLike struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=social.craftsky.feed.like"`
	// createdAt: Client-declared creation timestamp of the like.
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	// subject: Strong reference to the post being liked.
	Subject *comatproto.RepoStrongRef `json:"subject" cborgen:"subject"`
}
