// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: social.craftsky.project.sewing

package craftsky

// ProjectSewing_Details is a "details" in the social.craftsky.project.sewing schema.
//
// Sewing-specific fields attached to a project post when craftType is sewing.
type ProjectSewing_Details struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=social.craftsky.project.sewing#details"`
	// projectType: The kind of sewing project. Helps discovery so readers can filter on, e.g., only garment projects.
	ProjectType *string `json:"projectType,omitempty" cborgen:"projectType,omitempty"`
}
