// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: social.craftsky.project.defs

package craftsky

// ProjectDefs_Gauge is a "gauge" in the social.craftsky.project.defs schema.
//
// Structured stitch gauge measured over a stated distance. Rows are optional because many crafters record only stitch gauge.
type ProjectDefs_Gauge struct {
	// measurement: Measurement distance for the gauge swatch, interpreted with unit.
	Measurement int64 `json:"measurement" cborgen:"measurement"`
	// rows: Number of rows or rounds measured, when recorded.
	Rows *int64 `json:"rows,omitempty" cborgen:"rows,omitempty"`
	// stitches: Number of stitches measured across the gauge swatch.
	Stitches int64 `json:"stitches" cborgen:"stitches"`
	// unit: Measurement unit for the gauge swatch.
	Unit string `json:"unit" cborgen:"unit"`
}
