// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: social.craftsky.project.crochet

package craftsky

// ProjectCrochet_Details is a "details" in the social.craftsky.project.crochet schema.
//
// Crochet-specific fields attached to a project post when craftType is crochet.
type ProjectCrochet_Details struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=social.craftsky.project.crochet#details"`
	// finishedSize: Free-text finished size or dimensions, e.g. '38in bust', 'baby blanket 36in x 42in', 'adult medium', or '12cm tall'.
	FinishedSize *string `json:"finishedSize,omitempty" cborgen:"finishedSize,omitempty"`
	// gauge: Structured stitch gauge measured over a stated distance.
	Gauge *ProjectDefs_Gauge `json:"gauge,omitempty" cborgen:"gauge,omitempty"`
	// hookSizeMm: Metric hook size used. Clients may display US letter-size aliases, but records store the metric mm value.
	HookSizeMm *string `json:"hookSizeMm,omitempty" cborgen:"hookSizeMm,omitempty"`
	// projectSubtype: More specific crochet project category. Clients choose valid subtypes based on projectType; the lexicon keeps this open for forward compatibility.
	ProjectSubtype *string `json:"projectSubtype,omitempty" cborgen:"projectSubtype,omitempty"`
	// projectType: The kind of crochet project. Amigurumi is first-class because it is common enough to deserve its own token.
	ProjectType *string `json:"projectType,omitempty" cborgen:"projectType,omitempty"`
	// yarnWeight: Yarn weight category. Uses the shared Craftsky project yarn-weight vocabulary.
	YarnWeight *string `json:"yarnWeight,omitempty" cborgen:"yarnWeight,omitempty"`
}
