// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: social.craftsky.project.quilting

package craftsky

// ProjectQuilting_Details is a "details" in the social.craftsky.project.quilting schema.
//
// Quilting-specific fields attached to a project post when craftType is quilting.
type ProjectQuilting_Details struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=social.craftsky.project.quilting#details"`
	// piecingTechnique: How the quilt top is pieced.
	PiecingTechnique *string `json:"piecingTechnique,omitempty" cborgen:"piecingTechnique,omitempty"`
	// projectSubtype: More specific quilting project category. Clients choose valid subtypes based on projectType; the lexicon keeps this open for forward compatibility.
	ProjectSubtype *string `json:"projectSubtype,omitempty" cborgen:"projectSubtype,omitempty"`
	// projectType: The kind of quilt.
	ProjectType *string `json:"projectType,omitempty" cborgen:"projectType,omitempty"`
	// quiltingMethod: How the quilt layers are quilted or secured together.
	QuiltingMethod *string `json:"quiltingMethod,omitempty" cborgen:"quiltingMethod,omitempty"`
	// size: Free-text description of finished dimensions, e.g. '60in x 80in', 'queen', or 'throw, ~50in square'. Not range-queryable.
	Size *string `json:"size,omitempty" cborgen:"size,omitempty"`
}
