// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: social.craftsky.project.knitting

package craftsky

// ProjectKnitting_Details is a "details" in the social.craftsky.project.knitting schema.
//
// Knitting-specific fields attached to a project post when craftType is knitting.
type ProjectKnitting_Details struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=social.craftsky.project.knitting#details"`
	// finishedSize: Free-text finished size or dimensions, e.g. '42in chest', 'EU 39 socks', 'toddler size', or '180cm x 45cm scarf'.
	FinishedSize *string `json:"finishedSize,omitempty" cborgen:"finishedSize,omitempty"`
	// gauge: Structured stitch gauge measured over a stated distance.
	Gauge *ProjectDefs_Gauge `json:"gauge,omitempty" cborgen:"gauge,omitempty"`
	// needleSizeMm: Metric needle size used. Clients may display US or UK size aliases, but records store the metric mm value.
	NeedleSizeMm *string `json:"needleSizeMm,omitempty" cborgen:"needleSizeMm,omitempty"`
	// projectSubtype: More specific knitting project category. Clients choose valid subtypes based on projectType; the lexicon keeps this open for forward compatibility.
	ProjectSubtype *string `json:"projectSubtype,omitempty" cborgen:"projectSubtype,omitempty"`
	// projectType: The kind of knitting project.
	ProjectType *string `json:"projectType,omitempty" cborgen:"projectType,omitempty"`
	// yarnWeight: Yarn weight category. Tokens follow Craft Yarn Council standards.
	YarnWeight *string `json:"yarnWeight,omitempty" cborgen:"yarnWeight,omitempty"`
}
