// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package community

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

func (t *LocationAddress) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)
	fieldCount := 6

	if t.Locality == nil {
		fieldCount--
	}

	if t.Name == nil {
		fieldCount--
	}

	if t.PostalCode == nil {
		fieldCount--
	}

	if t.Region == nil {
		fieldCount--
	}

	if t.Street == nil {
		fieldCount--
	}

	if _, err := cw.Write(cbg.CborEncodeMajorType(cbg.MajMap, uint64(fieldCount))); err != nil {
		return err
	}

	// t.Name (string) (string)
	if t.Name != nil {

		if len("name") > 1000000 {
			return xerrors.Errorf("Value in field \"name\" was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("name"))); err != nil {
			return err
		}
		if _, err := cw.WriteString(string("name")); err != nil {
			return err
		}

		if t.Name == nil {
			if _, err := cw.Write(cbg.CborNull); err != nil {
				return err
			}
		} else {
			if len(*t.Name) > 1000000 {
				return xerrors.Errorf("Value in field t.Name was too long")
			}

			if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(*t.Name))); err != nil {
				return err
			}
			if _, err := cw.WriteString(string(*t.Name)); err != nil {
				return err
			}
		}
	}

	// t.Region (string) (string)
	if t.Region != nil {

		if len("region") > 1000000 {
			return xerrors.Errorf("Value in field \"region\" was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("region"))); err != nil {
			return err
		}
		if _, err := cw.WriteString(string("region")); err != nil {
			return err
		}

		if t.Region == nil {
			if _, err := cw.Write(cbg.CborNull); err != nil {
				return err
			}
		} else {
			if len(*t.Region) > 1000000 {
				return xerrors.Errorf("Value in field t.Region was too long")
			}

			if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(*t.Region))); err != nil {
				return err
			}
			if _, err := cw.WriteString(string(*t.Region)); err != nil {
				return err
			}
		}
	}

	// t.Street (string) (string)
	if t.Street != nil {

		if len("street") > 1000000 {
			return xerrors.Errorf("Value in field \"street\" was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("street"))); err != nil {
			return err
		}
		if _, err := cw.WriteString(string("street")); err != nil {
			return err
		}

		if t.Street == nil {
			if _, err := cw.Write(cbg.CborNull); err != nil {
				return err
			}
		} else {
			if len(*t.Street) > 1000000 {
				return xerrors.Errorf("Value in field t.Street was too long")
			}

			if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(*t.Street))); err != nil {
				return err
			}
			if _, err := cw.WriteString(string(*t.Street)); err != nil {
				return err
			}
		}
	}

	// t.Country (string) (string)
	if len("country") > 1000000 {
		return xerrors.Errorf("Value in field \"country\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("country"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("country")); err != nil {
		return err
	}

	if len(t.Country) > 1000000 {
		return xerrors.Errorf("Value in field t.Country was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Country))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.Country)); err != nil {
		return err
	}

	// t.Locality (string) (string)
	if t.Locality != nil {

		if len("locality") > 1000000 {
			return xerrors.Errorf("Value in field \"locality\" was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("locality"))); err != nil {
			return err
		}
		if _, err := cw.WriteString(string("locality")); err != nil {
			return err
		}

		if t.Locality == nil {
			if _, err := cw.Write(cbg.CborNull); err != nil {
				return err
			}
		} else {
			if len(*t.Locality) > 1000000 {
				return xerrors.Errorf("Value in field t.Locality was too long")
			}

			if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(*t.Locality))); err != nil {
				return err
			}
			if _, err := cw.WriteString(string(*t.Locality)); err != nil {
				return err
			}
		}
	}

	// t.PostalCode (string) (string)
	if t.PostalCode != nil {

		if len("postalCode") > 1000000 {
			return xerrors.Errorf("Value in field \"postalCode\" was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("postalCode"))); err != nil {
			return err
		}
		if _, err := cw.WriteString(string("postalCode")); err != nil {
			return err
		}

		if t.PostalCode == nil {
			if _, err := cw.Write(cbg.CborNull); err != nil {
				return err
			}
		} else {
			if len(*t.PostalCode) > 1000000 {
				return xerrors.Errorf("Value in field t.PostalCode was too long")
			}

			if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(*t.PostalCode))); err != nil {
				return err
			}
			if _, err := cw.WriteString(string(*t.PostalCode)); err != nil {
				return err
			}
		}
	}
	return nil
}

func (t *LocationAddress) UnmarshalCBOR(r io.Reader) (err error) {
	*t = LocationAddress{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("LocationAddress: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 10)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 1000000)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Name (string) (string)
		case "name":

			{
				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}

					sval, err := cbg.ReadStringWithMax(cr, 1000000)
					if err != nil {
						return err
					}

					t.Name = (*string)(&sval)
				}
			}
			// t.Region (string) (string)
		case "region":

			{
				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}

					sval, err := cbg.ReadStringWithMax(cr, 1000000)
					if err != nil {
						return err
					}

					t.Region = (*string)(&sval)
				}
			}
			// t.Street (string) (string)
		case "street":

			{
				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}

					sval, err := cbg.ReadStringWithMax(cr, 1000000)
					if err != nil {
						return err
					}

					t.Street = (*string)(&sval)
				}
			}
			// t.Country (string) (string)
		case "country":

			{
				sval, err := cbg.ReadStringWithMax(cr, 1000000)
				if err != nil {
					return err
				}

				t.Country = string(sval)
			}
			// t.Locality (string) (string)
		case "locality":

			{
				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}

					sval, err := cbg.ReadStringWithMax(cr, 1000000)
					if err != nil {
						return err
					}

					t.Locality = (*string)(&sval)
				}
			}
			// t.PostalCode (string) (string)
		case "postalCode":

			{
				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}

					sval, err := cbg.ReadStringWithMax(cr, 1000000)
					if err != nil {
						return err
					}

					t.PostalCode = (*string)(&sval)
				}
			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
