// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: community.lexicon.location.address

package community

// LocationAddress is a "main" in the community.lexicon.location.address schema.
//
// A physical location in the form of a street address.
type LocationAddress struct {
	// country: The ISO 3166 country code. Preferably the 2-letter code.
	Country string `json:"country" cborgen:"country"`
	// locality: The locality of the region. For example, a city in the USA.
	Locality *string `json:"locality,omitempty" cborgen:"locality,omitempty"`
	// name: The name of the location.
	Name *string `json:"name,omitempty" cborgen:"name,omitempty"`
	// postalCode: The postal code of the location.
	PostalCode *string `json:"postalCode,omitempty" cborgen:"postalCode,omitempty"`
	// region: The administrative region of the country. For example, a state in the USA.
	Region *string `json:"region,omitempty" cborgen:"region,omitempty"`
	// street: The street address.
	Street *string `json:"street,omitempty" cborgen:"street,omitempty"`
}
