package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/xml"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/net/html"
)

type currencyList struct {
	Entries []currencyEntry `xml:"CcyTbl>CcyNtry"`
}

type currencyEntry struct {
	Code       string `xml:"Ccy"`
	MinorUnits string `xml:"CcyMnrUnts"`
}

func main() {
	countryInput := flag.String("country-input", "internal/business/catalogdata/iso-3166-1-obp-2026-08-28.html", "ISO 3166-1 OBP rendered HTML")
	countrySHA := flag.String("country-sha256", "internal/business/catalogdata/iso-3166-1-obp-2026-08-28.sha256", "country source SHA-256 sidecar")
	countryOutput := flag.String("country-output", "internal/business/countries_generated.go", "generated country Go output")
	currencyInput := flag.String("currency-input", "internal/business/catalogdata/iso-4217-list-one-2026-08-28.xml", "SIX ISO 4217 List One XML")
	currencySHA := flag.String("currency-sha256", "internal/business/catalogdata/iso-4217-list-one-2026-08-28.sha256", "currency source SHA-256 sidecar")
	currencyOutput := flag.String("currency-output", "internal/business/currencies_generated.go", "generated Go output")
	check := flag.Bool("check", false, "fail if generated outputs differ without writing them")
	flag.Parse()

	if err := verifyDigest(*countryInput, *countrySHA); err != nil {
		fatalf("verify country input: %v", err)
	}
	countries, err := readCountries(*countryInput)
	if err != nil {
		fatalf("read countries: %v", err)
	}
	countrySource, err := generateCountries(countries)
	if err != nil {
		fatalf("generate countries: %v", err)
	}
	if err := writeOrCheck(*countryOutput, countrySource, *check); err != nil {
		fatalf("write countries: %v", err)
	}

	if err := verifyDigest(*currencyInput, *currencySHA); err != nil {
		fatalf("verify currency input: %v", err)
	}
	data, err := os.ReadFile(*currencyInput)
	if err != nil {
		fatalf("read currency input: %v", err)
	}
	var list currencyList
	if err := xml.Unmarshal(data, &list); err != nil {
		fatalf("decode currency input: %v", err)
	}

	scales := make(map[string]int)
	for _, entry := range list.Entries {
		if len(entry.Code) != 3 || entry.Code != strings.ToUpper(entry.Code) {
			continue
		}
		scale, err := strconv.Atoi(entry.MinorUnits)
		if err != nil || scale < 0 {
			continue
		}
		if existing, ok := scales[entry.Code]; ok && existing != scale {
			fatalf("currency %s has conflicting scales %d and %d", entry.Code, existing, scale)
		}
		scales[entry.Code] = scale
	}

	codes := make([]string, 0, len(scales))
	for code := range scales {
		codes = append(codes, code)
	}
	sort.Strings(codes)

	var source strings.Builder
	source.WriteString("// Code generated by businesscataloggen; DO NOT EDIT.\n\n")
	source.WriteString("package business\n\n")
	source.WriteString("var currencyMinorUnits = map[string]int{\n")
	for _, code := range codes {
		fmt.Fprintf(&source, "\t%q: %d,\n", code, scales[code])
	}
	source.WriteString("}\n")

	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		fatalf("format currency output: %v", err)
	}
	if err := writeOrCheck(*currencyOutput, formatted, *check); err != nil {
		fatalf("write currency output: %v", err)
	}
}

func readCountries(path string) ([]string, error) {
	input, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer input.Close()

	document, err := html.Parse(input)
	if err != nil {
		return nil, err
	}
	var cells []string
	var visit func(*html.Node)
	visit = func(node *html.Node) {
		if node.Type == html.ElementNode && attribute(node, "role") == "gridcell" {
			cells = append(cells, strings.TrimSpace(nodeText(node)))
		}
		for child := node.FirstChild; child != nil; child = child.NextSibling {
			visit(child)
		}
	}
	visit(document)
	if len(cells) != 249*5 {
		return nil, fmt.Errorf("found %d country cells, want %d", len(cells), 249*5)
	}

	seen := make(map[string]struct{}, 249)
	for index := 0; index < len(cells); index += 5 {
		code := cells[index+2]
		if len(code) != 2 || code != strings.ToUpper(code) {
			return nil, fmt.Errorf("invalid alpha-2 code %q", code)
		}
		if _, duplicate := seen[code]; duplicate {
			return nil, fmt.Errorf("duplicate alpha-2 code %q", code)
		}
		seen[code] = struct{}{}
	}
	codes := make([]string, 0, len(seen))
	for code := range seen {
		codes = append(codes, code)
	}
	sort.Strings(codes)
	return codes, nil
}

func generateCountries(codes []string) ([]byte, error) {
	var source strings.Builder
	source.WriteString("// Code generated by businesscataloggen; DO NOT EDIT.\n\n")
	source.WriteString("package business\n\n")
	source.WriteString("var assignedCountryCodes = map[string]struct{}{\n")
	for _, code := range codes {
		fmt.Fprintf(&source, "\t%q: {},\n", code)
	}
	source.WriteString("}\n")
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, err
	}
	return formatted, nil
}

func verifyDigest(sourcePath, sidecarPath string) error {
	source, err := os.ReadFile(sourcePath)
	if err != nil {
		return err
	}
	sidecar, err := os.ReadFile(sidecarPath)
	if err != nil {
		return err
	}
	fields := strings.Fields(string(sidecar))
	if len(fields) < 1 {
		return fmt.Errorf("empty digest sidecar")
	}
	digest := sha256.Sum256(source)
	if hex.EncodeToString(digest[:]) != fields[0] {
		return fmt.Errorf("source digest does not match sidecar")
	}
	return nil
}

func writeOrCheck(path string, generated []byte, check bool) error {
	if !check {
		return os.WriteFile(path, generated, 0o644)
	}
	existing, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if !bytes.Equal(existing, generated) {
		return fmt.Errorf("%s is stale", path)
	}
	return nil
}

func attribute(node *html.Node, key string) string {
	for _, attribute := range node.Attr {
		if attribute.Key == key {
			return attribute.Val
		}
	}
	return ""
}

func nodeText(node *html.Node) string {
	if node.Type == html.TextNode {
		return node.Data
	}
	var text strings.Builder
	for child := node.FirstChild; child != nil; child = child.NextSibling {
		text.WriteString(nodeText(child))
	}
	return text.String()
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
