import 'package:craftsky_app/feed/models/post.dart';

final _createdAt = DateTime.utc(2026, 5, 4, 18, 23, 45);
final _indexedAt = DateTime.utc(2026, 5, 4, 18, 23, 47);

Post postFixture({
  String did = 'did:plc:alice',
  String handle = 'alice.craftsky.social',
  String rkey = '3lf2abc',
  String text = 'hello',
  List<String> tags = const [],
  List<String> langs = const ['en'],
  int likeCount = 0,
  int repostCount = 0,
  int replyCount = 0,
  bool viewerHasLiked = false,
  bool viewerHasReposted = false,
  bool viewerHasSaved = false,
  bool sponsored = false,
}) => Post(
  uri: 'at://$did/social.craftsky.feed.post/$rkey',
  cid: 'bafy$rkey',
  rkey: rkey,
  text: text,
  tags: tags,
  langs: langs,
  createdAt: _createdAt,
  indexedAt: _indexedAt,
  author: PostAuthor(did: did, handle: handle),
  likeCount: likeCount,
  repostCount: repostCount,
  replyCount: replyCount,
  viewerHasLiked: viewerHasLiked,
  viewerHasReposted: viewerHasReposted,
  viewerHasSaved: viewerHasSaved,
  sponsored: sponsored,
);

Map<String, dynamic> postWirePayload({
  String did = 'did:plc:alice',
  String handle = 'alice.craftsky.social',
  String rkey = '3lf2abc',
  String text = 'hello',
  List<String> tags = const [],
  List<String> langs = const ['en'],
  int likeCount = 0,
  int repostCount = 0,
  int replyCount = 0,
  bool viewerHasLiked = false,
  bool viewerHasReposted = false,
  bool viewerHasSaved = false,
  bool sponsored = false,
}) => {
  'uri': 'at://$did/social.craftsky.feed.post/$rkey',
  'cid': 'bafy$rkey',
  'rkey': rkey,
  'text': text,
  'tags': [...tags],
  'langs': [...langs],
  'createdAt': _createdAt.toIso8601String(),
  'indexedAt': _indexedAt.toIso8601String(),
  'author': {'did': did, 'handle': handle},
  'likeCount': likeCount,
  'repostCount': repostCount,
  'replyCount': replyCount,
  'viewerHasLiked': viewerHasLiked,
  'viewerHasReposted': viewerHasReposted,
  'viewerHasSaved': viewerHasSaved,
  'sponsored': sponsored,
};
