import 'package:craftsky_app/l10n/generated/app_localizations_en.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test(
    'subscription settings, states, actions, and semantics are localized',
    () {
      final l10n = AppLocalizationsEn();
      final values = <String>[
        l10n.subscriptionsTitle,
        l10n.subscriptionsTierFree,
        l10n.subscriptionsTierPlus,
        l10n.subscriptionsTierBusiness,
        l10n.subscriptionsTierLoading,
        l10n.subscriptionsTierUnavailable,
        l10n.subscriptionsEffectiveAccess('Plus'),
        l10n.subscriptionsDormantAssignment('Plus'),
        l10n.subscriptionsBeneficiaryExplanation,
        l10n.subscriptionsSwitchToOwner,
        l10n.subscriptionsChooseOwnerTitle,
        l10n.subscriptionsChooseOwnerBody,
        l10n.subscriptionsChooseOwnerAction,
        l10n.subscriptionsSetupIncomplete,
        l10n.subscriptionsRetrySetup,
        l10n.subscriptionsOwnerInactive,
        l10n.subscriptionsOwnerReauthenticate,
        l10n.subscriptionsIndependentLicenses,
        l10n.subscriptionsStatusAvailable,
        l10n.subscriptionsStatusActive,
        l10n.subscriptionsStatusCanceledAccessible,
        l10n.subscriptionsStatusDormant,
        l10n.subscriptionsStatusStale,
        l10n.subscriptionsStatusPending,
        l10n.subscriptionsStatusAnomaly,
        l10n.subscriptionsStatusUnavailable,
        l10n.subscriptionsAssignedTo('@alice.test'),
        l10n.subscriptionsUnassigned,
        l10n.subscriptionsProductContext('app_store', 'plus'),
        l10n.subscriptionsCurrentPeriod('Sep 1, 2026', 'Oct 1, 2026'),
        l10n.subscriptionsAccessEnds('Oct 1, 2026'),
        l10n.subscriptionsRenewsOn('Oct 1, 2026'),
        l10n.subscriptionsAccessUntil('Oct 1, 2026'),
        l10n.subscriptionsLicenseAssignable,
        l10n.subscriptionsLicenseNotAssignable,
        l10n.subscriptionsReconciliationRequested('Sep 10, 2026'),
        l10n.subscriptionsLastReconciled('Sep 11, 2026'),
        l10n.subscriptionsPurchase('Plus'),
        l10n.subscriptionsRepurchase('Plus'),
        l10n.subscriptionsAssign,
        l10n.subscriptionsUnassign,
        l10n.subscriptionsRestore,
        l10n.subscriptionsManage,
        l10n.subscriptionsRefresh,
        l10n.subscriptionsBillingUnavailable,
        l10n.subscriptionsOfferingUnavailable,
        l10n.subscriptionsProviderFailure,
        l10n.subscriptionsAssignmentConflict,
        l10n.subscriptionsAssignmentCooldown,
        l10n.subscriptionsLicenseNotFound,
        l10n.subscriptionsTargetIneligible,
        l10n.subscriptionsUnauthorized,
        l10n.subscriptionsActionFailed,
        l10n.subscriptionsPendingRefresh,
        l10n.subscriptionsActionSemantic('Plus', 'Active', 'Assign'),
        l10n.subscriptionsAssignmentConfirmTitle,
        l10n.subscriptionsAssignmentConfirmBody('Plus', '@alice.test'),
        l10n.subscriptionsReassign,
        l10n.subscriptionsReassignmentConfirmTitle,
        l10n.subscriptionsUnassignmentConfirmTitle,
        l10n.subscriptionsUnassignmentConfirmBody,
      ];

      expect(values, everyElement(isNotEmpty));
    },
  );
}
