// Run from appview: go run ../scripts/generate-hashtag-case-map.go
// Keep SQL spelling votes and Flutter pagination aligned with Go tag identities.
package main

import (
	"fmt"
	"os"
	"strings"
	"unicode"
)

func main() {
	var upper, lower []rune
	for r := rune(0); r <= unicode.MaxRune; r++ {
		if mapped := unicode.ToLower(r); mapped != r {
			upper = append(upper, r)
			lower = append(lower, mapped)
		}
	}
	const migration = "migrations/000090_hashtag_spellings.up.sql"
	body, err := os.ReadFile(migration)
	check(err)
	_, remainder, ok := strings.Cut(string(body), "-- encoding/json matches")
	if !ok {
		panic("cannot find migration case-map boundary")
	}
	sql := fmt.Sprintf(`-- Generated by scripts/generate-hashtag-case-map.go; Go Unicode %s.
-- Go simple lowercase mappings are independent of database locale/libc.
-- TestHashtagSpellingsUnicodeNormalization checks toolchain parity.
CREATE FUNCTION craftsky_tag_lower(value TEXT) RETURNS TEXT
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT AS $$
    SELECT CASE WHEN octet_length(value) = length(value)
        THEN translate(value, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')
        ELSE translate(value,
        '%s',
        '%s') END;
$$;

-- encoding/json matches`, unicode.Version, string(upper), string(lower))
	check(os.WriteFile(migration, []byte(sql+remainder), 0644))

	var dart strings.Builder
	fmt.Fprintf(&dart, `// Generated by scripts/generate-hashtag-case-map.go; Go Unicode %s.
// Regenerate from appview with: go run ../scripts/generate-hashtag-case-map.go

/// Uses the AppView's simple Unicode lowercase rules for hashtag identity.
/// Display spelling remains unchanged; Dart/platform casing versions may differ.
String hashtagIdentity(String tag) => String.fromCharCodes(
  tag.runes.map((rune) => _lowercaseRunes[rune] ?? rune),
);

final _lowercaseRunes = Map<int, int>.fromIterables(
  _uppercase.runes,
  _lowercase.runes,
);

`, unicode.Version)
	for _, item := range []struct {
		name string
		text []rune
	}{{"_uppercase", upper}, {"_lowercase", lower}} {
		fmt.Fprintf(&dart, "const %s =\n", item.name)
		for start := 0; start < len(item.text); start += 16 {
			end := min(start+16, len(item.text))
			suffix := ""
			if end == len(item.text) {
				suffix = ";"
			}
			fmt.Fprintf(&dart, "    '%s'%s\n", string(item.text[start:end]), suffix)
		}
		dart.WriteString("\n")
	}
	check(os.WriteFile("../app/lib/search/models/hashtag_identity.dart", []byte(dart.String()), 0644))
}

func check(err error) {
	if err != nil {
		panic(err)
	}
}
