-- Generated by scripts/generate-hashtag-case-map.go; Go Unicode 17.0.0.
-- Go simple lowercase mappings are independent of database locale/libc.
-- TestHashtagSpellingsUnicodeNormalization checks toolchain parity.
CREATE FUNCTION craftsky_tag_lower(value TEXT) RETURNS TEXT
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT AS $$
    SELECT CASE WHEN octet_length(value) = length(value)
        THEN translate(value, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')
        ELSE translate(value,
        'ABCDEFGHIJKLMNOPQRSTUVWXYZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞĀĂĄĆĈĊČĎĐĒĔĖĘĚĜĞĠĢĤĦĨĪĬĮİĲĴĶĹĻĽĿŁŃŅŇŊŌŎŐŒŔŖŘŚŜŞŠŢŤŦŨŪŬŮŰŲŴŶŸŹŻŽƁƂƄƆƇƉƊƋƎƏƐƑƓƔƖƗƘƜƝƟƠƢƤƦƧƩƬƮƯƱƲƳƵƷƸƼǄǅǇǈǊǋǍǏǑǓǕǗǙǛǞǠǢǤǦǨǪǬǮǱǲǴǶǷǸǺǼǾȀȂȄȆȈȊȌȎȐȒȔȖȘȚȜȞȠȢȤȦȨȪȬȮȰȲȺȻȽȾɁɃɄɅɆɈɊɌɎͰͲͶͿΆΈΉΊΌΎΏΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΪΫϏϘϚϜϞϠϢϤϦϨϪϬϮϴϷϹϺϽϾϿЀЁЂЃЄЅІЇЈЉЊЋЌЍЎЏАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯѠѢѤѦѨѪѬѮѰѲѴѶѸѺѼѾҀҊҌҎҐҒҔҖҘҚҜҞҠҢҤҦҨҪҬҮҰҲҴҶҸҺҼҾӀӁӃӅӇӉӋӍӐӒӔӖӘӚӜӞӠӢӤӦӨӪӬӮӰӲӴӶӸӺӼӾԀԂԄԆԈԊԌԎԐԒԔԖԘԚԜԞԠԢԤԦԨԪԬԮԱԲԳԴԵԶԷԸԹԺԻԼԽԾԿՀՁՂՃՄՅՆՇՈՉՊՋՌՍՎՏՐՑՒՓՔՕՖႠႡႢႣႤႥႦႧႨႩႪႫႬႭႮႯႰႱႲႳႴႵႶႷႸႹႺႻႼႽႾႿჀჁჂჃჄჅჇჍᎠᎡᎢᎣᎤᎥᎦᎧᎨᎩᎪᎫᎬᎭᎮᎯᎰᎱᎲᎳᎴᎵᎶᎷᎸᎹᎺᎻᎼᎽᎾᎿᏀᏁᏂᏃᏄᏅᏆᏇᏈᏉᏊᏋᏌᏍᏎᏏᏐᏑᏒᏓᏔᏕᏖᏗᏘᏙᏚᏛᏜᏝᏞᏟᏠᏡᏢᏣᏤᏥᏦᏧᏨᏩᏪᏫᏬᏭᏮᏯᏰᏱᏲᏳᏴᏵᲉᲐᲑᲒᲓᲔᲕᲖᲗᲘᲙᲚᲛᲜᲝᲞᲟᲠᲡᲢᲣᲤᲥᲦᲧᲨᲩᲪᲫᲬᲭᲮᲯᲰᲱᲲᲳᲴᲵᲶᲷᲸᲹᲺᲽᲾᲿḀḂḄḆḈḊḌḎḐḒḔḖḘḚḜḞḠḢḤḦḨḪḬḮḰḲḴḶḸḺḼḾṀṂṄṆṈṊṌṎṐṒṔṖṘṚṜṞṠṢṤṦṨṪṬṮṰṲṴṶṸṺṼṾẀẂẄẆẈẊẌẎẐẒẔẞẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼẾỀỂỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪỬỮỰỲỴỶỸỺỼỾἈἉἊἋἌἍἎἏἘἙἚἛἜἝἨἩἪἫἬἭἮἯἸἹἺἻἼἽἾἿὈὉὊὋὌὍὙὛὝὟὨὩὪὫὬὭὮὯᾈᾉᾊᾋᾌᾍᾎᾏᾘᾙᾚᾛᾜᾝᾞᾟᾨᾩᾪᾫᾬᾭᾮᾯᾸᾹᾺΆᾼῈΈῊΉῌῘῙῚΊῨῩῪΎῬῸΌῺΏῼΩKÅℲⅠⅡⅢⅣⅤⅥⅦⅧⅨⅩⅪⅫⅬⅭⅮⅯↃⒶⒷⒸⒹⒺⒻⒼⒽⒾⒿⓀⓁⓂⓃⓄⓅⓆⓇⓈⓉⓊⓋⓌⓍⓎⓏⰀⰁⰂⰃⰄⰅⰆⰇⰈⰉⰊⰋⰌⰍⰎⰏⰐⰑⰒⰓⰔⰕⰖⰗⰘⰙⰚⰛⰜⰝⰞⰟⰠⰡⰢⰣⰤⰥⰦⰧⰨⰩⰪⰫⰬⰭⰮⰯⱠⱢⱣⱤⱧⱩⱫⱭⱮⱯⱰⱲⱵⱾⱿⲀⲂⲄⲆⲈⲊⲌⲎⲐⲒⲔⲖⲘⲚⲜⲞⲠⲢⲤⲦⲨⲪⲬⲮⲰⲲⲴⲶⲸⲺⲼⲾⳀⳂⳄⳆⳈⳊⳌⳎⳐⳒⳔⳖⳘⳚⳜⳞⳠⳢⳫⳭⳲꙀꙂꙄꙆꙈꙊꙌꙎꙐꙒꙔꙖꙘꙚꙜꙞꙠꙢꙤꙦꙨꙪꙬꚀꚂꚄꚆꚈꚊꚌꚎꚐꚒꚔꚖꚘꚚꜢꜤꜦꜨꜪꜬꜮꜲꜴꜶꜸꜺꜼꜾꝀꝂꝄꝆꝈꝊꝌꝎꝐꝒꝔꝖꝘꝚꝜꝞꝠꝢꝤꝦꝨꝪꝬꝮꝹꝻꝽꝾꞀꞂꞄꞆꞋꞍꞐꞒꞖꞘꞚꞜꞞꞠꞢꞤꞦꞨꞪꞫꞬꞭꞮꞰꞱꞲꞳꞴꞶꞸꞺꞼꞾꟀꟂꟄꟅꟆꟇꟉꟋꟌ꟎Ꟑ꟒꟔ꟖꟘꟚꟜꟵＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺ𐐀𐐁𐐂𐐃𐐄𐐅𐐆𐐇𐐈𐐉𐐊𐐋𐐌𐐍𐐎𐐏𐐐𐐑𐐒𐐓𐐔𐐕𐐖𐐗𐐘𐐙𐐚𐐛𐐜𐐝𐐞𐐟𐐠𐐡𐐢𐐣𐐤𐐥𐐦𐐧𐒰𐒱𐒲𐒳𐒴𐒵𐒶𐒷𐒸𐒹𐒺𐒻𐒼𐒽𐒾𐒿𐓀𐓁𐓂𐓃𐓄𐓅𐓆𐓇𐓈𐓉𐓊𐓋𐓌𐓍𐓎𐓏𐓐𐓑𐓒𐓓𐕰𐕱𐕲𐕳𐕴𐕵𐕶𐕷𐕸𐕹𐕺𐕼𐕽𐕾𐕿𐖀𐖁𐖂𐖃𐖄𐖅𐖆𐖇𐖈𐖉𐖊𐖌𐖍𐖎𐖏𐖐𐖑𐖒𐖔𐖕𐲀𐲁𐲂𐲃𐲄𐲅𐲆𐲇𐲈𐲉𐲊𐲋𐲌𐲍𐲎𐲏𐲐𐲑𐲒𐲓𐲔𐲕𐲖𐲗𐲘𐲙𐲚𐲛𐲜𐲝𐲞𐲟𐲠𐲡𐲢𐲣𐲤𐲥𐲦𐲧𐲨𐲩𐲪𐲫𐲬𐲭𐲮𐲯𐲰𐲱𐲲𐵐𐵑𐵒𐵓𐵔𐵕𐵖𐵗𐵘𐵙𐵚𐵛𐵜𐵝𐵞𐵟𐵠𐵡𐵢𐵣𐵤𐵥𑢠𑢡𑢢𑢣𑢤𑢥𑢦𑢧𑢨𑢩𑢪𑢫𑢬𑢭𑢮𑢯𑢰𑢱𑢲𑢳𑢴𑢵𑢶𑢷𑢸𑢹𑢺𑢻𑢼𑢽𑢾𑢿𖹀𖹁𖹂𖹃𖹄𖹅𖹆𖹇𖹈𖹉𖹊𖹋𖹌𖹍𖹎𖹏𖹐𖹑𖹒𖹓𖹔𖹕𖹖𖹗𖹘𖹙𖹚𖹛𖹜𖹝𖹞𖹟𖺠𖺡𖺢𖺣𖺤𖺥𖺦𖺧𖺨𖺩𖺪𖺫𖺬𖺭𖺮𖺯𖺰𖺱𖺲𖺳𖺴𖺵𖺶𖺷𖺸𞤀𞤁𞤂𞤃𞤄𞤅𞤆𞤇𞤈𞤉𞤊𞤋𞤌𞤍𞤎𞤏𞤐𞤑𞤒𞤓𞤔𞤕𞤖𞤗𞤘𞤙𞤚𞤛𞤜𞤝𞤞𞤟𞤠𞤡',
        'abcdefghijklmnopqrstuvwxyzàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþāăąćĉċčďđēĕėęěĝğġģĥħĩīĭįiĳĵķĺļľŀłńņňŋōŏőœŕŗřśŝşšţťŧũūŭůűųŵŷÿźżžɓƃƅɔƈɖɗƌǝəɛƒɠɣɩɨƙɯɲɵơƣƥʀƨʃƭʈưʊʋƴƶʒƹƽǆǆǉǉǌǌǎǐǒǔǖǘǚǜǟǡǣǥǧǩǫǭǯǳǳǵƕƿǹǻǽǿȁȃȅȇȉȋȍȏȑȓȕȗșțȝȟƞȣȥȧȩȫȭȯȱȳⱥȼƚⱦɂƀʉʌɇɉɋɍɏͱͳͷϳάέήίόύώαβγδεζηθικλμνξοπρστυφχψωϊϋϗϙϛϝϟϡϣϥϧϩϫϭϯθϸϲϻͻͼͽѐёђѓєѕіїјљњћќѝўџабвгдежзийклмнопрстуфхцчшщъыьэюяѡѣѥѧѩѫѭѯѱѳѵѷѹѻѽѿҁҋҍҏґғҕҗҙқҝҟҡңҥҧҩҫҭүұҳҵҷҹһҽҿӏӂӄӆӈӊӌӎӑӓӕӗәӛӝӟӡӣӥӧөӫӭӯӱӳӵӷӹӻӽӿԁԃԅԇԉԋԍԏԑԓԕԗԙԛԝԟԡԣԥԧԩԫԭԯաբգդեզէըթժիլխծկհձղճմյնշոչպջռսվտրցւփքօֆⴀⴁⴂⴃⴄⴅⴆⴇⴈⴉⴊⴋⴌⴍⴎⴏⴐⴑⴒⴓⴔⴕⴖⴗⴘⴙⴚⴛⴜⴝⴞⴟⴠⴡⴢⴣⴤⴥⴧⴭꭰꭱꭲꭳꭴꭵꭶꭷꭸꭹꭺꭻꭼꭽꭾꭿꮀꮁꮂꮃꮄꮅꮆꮇꮈꮉꮊꮋꮌꮍꮎꮏꮐꮑꮒꮓꮔꮕꮖꮗꮘꮙꮚꮛꮜꮝꮞꮟꮠꮡꮢꮣꮤꮥꮦꮧꮨꮩꮪꮫꮬꮭꮮꮯꮰꮱꮲꮳꮴꮵꮶꮷꮸꮹꮺꮻꮼꮽꮾꮿᏸᏹᏺᏻᏼᏽᲊაბგდევზთიკლმნოპჟრსტუფქღყშჩცძწჭხჯჰჱჲჳჴჵჶჷჸჹჺჽჾჿḁḃḅḇḉḋḍḏḑḓḕḗḙḛḝḟḡḣḥḧḩḫḭḯḱḳḵḷḹḻḽḿṁṃṅṇṉṋṍṏṑṓṕṗṙṛṝṟṡṣṥṧṩṫṭṯṱṳṵṷṹṻṽṿẁẃẅẇẉẋẍẏẑẓẕßạảấầẩẫậắằẳẵặẹẻẽếềểễệỉịọỏốồổỗộớờởỡợụủứừửữựỳỵỷỹỻỽỿἀἁἂἃἄἅἆἇἐἑἒἓἔἕἠἡἢἣἤἥἦἧἰἱἲἳἴἵἶἷὀὁὂὃὄὅὑὓὕὗὠὡὢὣὤὥὦὧᾀᾁᾂᾃᾄᾅᾆᾇᾐᾑᾒᾓᾔᾕᾖᾗᾠᾡᾢᾣᾤᾥᾦᾧᾰᾱὰάᾳὲέὴήῃῐῑὶίῠῡὺύῥὸόὼώῳωkåⅎⅰⅱⅲⅳⅴⅵⅶⅷⅸⅹⅺⅻⅼⅽⅾⅿↄⓐⓑⓒⓓⓔⓕⓖⓗⓘⓙⓚⓛⓜⓝⓞⓟⓠⓡⓢⓣⓤⓥⓦⓧⓨⓩⰰⰱⰲⰳⰴⰵⰶⰷⰸⰹⰺⰻⰼⰽⰾⰿⱀⱁⱂⱃⱄⱅⱆⱇⱈⱉⱊⱋⱌⱍⱎⱏⱐⱑⱒⱓⱔⱕⱖⱗⱘⱙⱚⱛⱜⱝⱞⱟⱡɫᵽɽⱨⱪⱬɑɱɐɒⱳⱶȿɀⲁⲃⲅⲇⲉⲋⲍⲏⲑⲓⲕⲗⲙⲛⲝⲟⲡⲣⲥⲧⲩⲫⲭⲯⲱⲳⲵⲷⲹⲻⲽⲿⳁⳃⳅⳇⳉⳋⳍⳏⳑⳓⳕⳗⳙⳛⳝⳟⳡⳣⳬⳮⳳꙁꙃꙅꙇꙉꙋꙍꙏꙑꙓꙕꙗꙙꙛꙝꙟꙡꙣꙥꙧꙩꙫꙭꚁꚃꚅꚇꚉꚋꚍꚏꚑꚓꚕꚗꚙꚛꜣꜥꜧꜩꜫꜭꜯꜳꜵꜷꜹꜻꜽꜿꝁꝃꝅꝇꝉꝋꝍꝏꝑꝓꝕꝗꝙꝛꝝꝟꝡꝣꝥꝧꝩꝫꝭꝯꝺꝼᵹꝿꞁꞃꞅꞇꞌɥꞑꞓꞗꞙꞛꞝꞟꞡꞣꞥꞧꞩɦɜɡɬɪʞʇʝꭓꞵꞷꞹꞻꞽꞿꟁꟃꞔʂᶎꟈꟊɤꟍ꟏ꟑꟓꟕꟗꟙꟛƛꟶａｂｃｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗｘｙｚ𐐨𐐩𐐪𐐫𐐬𐐭𐐮𐐯𐐰𐐱𐐲𐐳𐐴𐐵𐐶𐐷𐐸𐐹𐐺𐐻𐐼𐐽𐐾𐐿𐑀𐑁𐑂𐑃𐑄𐑅𐑆𐑇𐑈𐑉𐑊𐑋𐑌𐑍𐑎𐑏𐓘𐓙𐓚𐓛𐓜𐓝𐓞𐓟𐓠𐓡𐓢𐓣𐓤𐓥𐓦𐓧𐓨𐓩𐓪𐓫𐓬𐓭𐓮𐓯𐓰𐓱𐓲𐓳𐓴𐓵𐓶𐓷𐓸𐓹𐓺𐓻𐖗𐖘𐖙𐖚𐖛𐖜𐖝𐖞𐖟𐖠𐖡𐖣𐖤𐖥𐖦𐖧𐖨𐖩𐖪𐖫𐖬𐖭𐖮𐖯𐖰𐖱𐖳𐖴𐖵𐖶𐖷𐖸𐖹𐖻𐖼𐳀𐳁𐳂𐳃𐳄𐳅𐳆𐳇𐳈𐳉𐳊𐳋𐳌𐳍𐳎𐳏𐳐𐳑𐳒𐳓𐳔𐳕𐳖𐳗𐳘𐳙𐳚𐳛𐳜𐳝𐳞𐳟𐳠𐳡𐳢𐳣𐳤𐳥𐳦𐳧𐳨𐳩𐳪𐳫𐳬𐳭𐳮𐳯𐳰𐳱𐳲𐵰𐵱𐵲𐵳𐵴𐵵𐵶𐵷𐵸𐵹𐵺𐵻𐵼𐵽𐵾𐵿𐶀𐶁𐶂𐶃𐶄𐶅𑣀𑣁𑣂𑣃𑣄𑣅𑣆𑣇𑣈𑣉𑣊𑣋𑣌𑣍𑣎𑣏𑣐𑣑𑣒𑣓𑣔𑣕𑣖𑣗𑣘𑣙𑣚𑣛𑣜𑣝𑣞𑣟𖹠𖹡𖹢𖹣𖹤𖹥𖹦𖹧𖹨𖹩𖹪𖹫𖹬𖹭𖹮𖹯𖹰𖹱𖹲𖹳𖹴𖹵𖹶𖹷𖹸𖹹𖹺𖹻𖹼𖹽𖹾𖹿𖺻𖺼𖺽𖺾𖺿𖻀𖻁𖻂𖻃𖻄𖻅𖻆𖻇𖻈𖻉𖻊𖻋𖻌𖻍𖻎𖻏𖻐𖻑𖻒𖻓𞤢𞤣𞤤𞤥𞤦𞤧𞤨𞤩𞤪𞤫𞤬𞤭𞤮𞤯𞤰𞤱𞤲𞤳𞤴𞤵𞤶𞤷𞤸𞤹𞤺𞤻𞤼𞤽𞤾𞤿𞥀𞥁𞥂𞥃') END;
$$;

-- encoding/json matches these ASCII schema field names case-insensitively.
-- SimpleFold additionally matches long s and Kelvin sign to ASCII S and K.
-- Accepted source objects have at most one key matching a recognized field.
-- The preflight and CHECK constraint below enforce this before projection.
CREATE FUNCTION craftsky_tag_field(object JSONB, field TEXT) RETURNS JSONB
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT AS $$
    SELECT value
    FROM jsonb_each(CASE WHEN jsonb_typeof(object) = 'object' THEN object ELSE '{}'::jsonb END)
    WHERE translate(key, 'ABCDEFGHIJKLMNOPQRSTUVWXYZſK', 'abcdefghijklmnopqrstuvwxyzsk')
        = translate(field, 'ABCDEFGHIJKLMNOPQRSTUVWXYZſK', 'abcdefghijklmnopqrstuvwxyzsk')
    LIMIT 1;
$$;

-- Only detect ambiguity at recognized hashtag-source boundaries. This is not
-- broad lexicon validation: unknown fields/features and malformed best-effort
-- facet payloads keep their existing handling. Matches postutil's raw checker;
-- JSONB cannot expose duplicate exact keys already overwritten during storage.
CREATE FUNCTION craftsky_tag_source_unambiguous(value JSONB, shape TEXT) RETURNS BOOLEAN
LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE AS $$
DECLARE
    rules JSONB;
    field RECORD;
    child TEXT;
    item JSONB;
    feature_type TEXT;
BEGIN
    IF right(shape, 2) = '[]' THEN
        IF jsonb_typeof(value) IS DISTINCT FROM 'array' THEN RETURN true; END IF;
        FOR item IN SELECT v FROM jsonb_array_elements(value) AS a(v) LOOP
            IF NOT craftsky_tag_source_unambiguous(item, left(shape, length(shape)-2)) THEN RETURN false; END IF;
        END LOOP;
        RETURN true;
    END IF;
    IF jsonb_typeof(value) IS DISTINCT FROM 'object' THEN RETURN true; END IF;
    rules := CASE shape
        WHEN 'post' THEN '{"text":"","facets":"facet[]","project":"project"}'::jsonb
        WHEN 'project' THEN '{"common":"common"}'::jsonb
        WHEN 'common' THEN '{"crafttype":"","tags":"","pattern":"pattern","materials":"material[]"}'::jsonb
        WHEN 'pattern' THEN '{"name":"","namefacets":"facet[]","designer":"","designerfacets":"facet[]","publisher":"","publisherfacets":"facet[]"}'::jsonb
        WHEN 'material' THEN '{"text":"","facets":"facet[]"}'::jsonb
        WHEN 'facet' THEN '{"index":"index","features":"feature[]"}'::jsonb
        WHEN 'index' THEN '{"bytestart":"","byteend":""}'::jsonb
        WHEN 'feature' THEN '{"$type":""}'::jsonb
        ELSE '{}'::jsonb END;
    IF shape = 'feature' THEN
        feature_type := craftsky_tag_field(value, '$type')#>>'{}';
        rules := rules || CASE feature_type
            WHEN 'app.bsky.richtext.facet#tag' THEN '{"tag":""}'::jsonb
            WHEN 'app.bsky.richtext.facet#mention' THEN '{"did":""}'::jsonb
            WHEN 'app.bsky.richtext.facet#link' THEN '{"uri":""}'::jsonb
            ELSE '{}'::jsonb END;
    END IF;
    IF EXISTS (
        SELECT 1 FROM jsonb_each(value)
        WHERE rules ? translate(key, 'ABCDEFGHIJKLMNOPQRSTUVWXYZſK', 'abcdefghijklmnopqrstuvwxyzsk')
        GROUP BY translate(key, 'ABCDEFGHIJKLMNOPQRSTUVWXYZſK', 'abcdefghijklmnopqrstuvwxyzsk') COLLATE "C"
        HAVING count(*) > 1
    ) THEN RETURN false; END IF;
    FOR field IN SELECT key, v FROM jsonb_each(value) AS a(key, v) LOOP
        child := rules ->> translate(field.key, 'ABCDEFGHIJKLMNOPQRSTUVWXYZſK', 'abcdefghijklmnopqrstuvwxyzsk');
        IF child <> '' AND NOT craftsky_tag_source_unambiguous(field.v, child) THEN RETURN false; END IF;
    END LOOP;
    RETURN true;
END;
$$;

-- Fail before adding the spelling projection; never guess, repair or omit
-- historical ambiguous records. A failed migration rolls back its schema work.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM craftsky_posts WHERE NOT craftsky_tag_source_unambiguous(record, 'post')) THEN
        RAISE EXCEPTION 'ambiguous hashtag source fields prevent spelling recovery'
            USING ERRCODE = '23514', HINT = 'Resolve conflicting recognized field aliases explicitly before retrying; source records were not modified.';
    END IF;
END;
$$;

-- Protect writes from older binaries or callers bypassing source validation.
ALTER TABLE craftsky_posts ADD CONSTRAINT craftsky_posts_unambiguous_tag_source
    CHECK (craftsky_tag_source_unambiguous(record, 'post'));

-- Match Go strings.TrimSpace (Unicode White_Space), not SQL's space-only trim.
CREATE FUNCTION craftsky_tag_trim(value TEXT) RETURNS TEXT
LANGUAGE SQL IMMUTABLE PARALLEL SAFE AS $$
    SELECT btrim(value, U&'\0009\000A\000B\000C\000D\0020\0085\00A0\1680\2000\2001\2002\2003\2004\2005\2006\2007\2008\2009\200A\2028\2029\202F\205F\3000');
$$;

-- Best-effort decoding mirrors postutil.DecodeFacets: a malformed typed value
-- invalidates this whole sibling facet array; unknown feature types are ignored.
CREATE FUNCTION craftsky_facet_tag_spellings(body TEXT, facets JSONB) RETURNS TEXT[]
LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE AS $$
DECLARE
    facet JSONB;
    feature JSONB;
    idx JSONB;
    raw_value JSONB;
    raw_features JSONB;
    raw_feature_type JSONB;
    field TEXT;
    feature_type TEXT;
    start_byte BIGINT;
    end_byte BIGINT;
    spelling TEXT;
    result TEXT[] := '{}';
BEGIN
    IF facets IS NULL OR facets = 'null'::jsonb THEN RETURN result; END IF;
    IF jsonb_typeof(facets) <> 'array' THEN RETURN result; END IF;
    FOR facet IN SELECT value FROM jsonb_array_elements(facets) LOOP
        IF facet = 'null'::jsonb THEN CONTINUE; END IF;
        IF jsonb_typeof(facet) <> 'object' THEN RETURN '{}'; END IF;
        idx := craftsky_tag_field(facet, 'index');
        IF idx IS NOT NULL AND idx <> 'null'::jsonb THEN
            IF jsonb_typeof(idx) <> 'object' THEN RETURN '{}'; END IF;
            FOREACH field IN ARRAY ARRAY['byteStart', 'byteEnd'] LOOP
                raw_value := craftsky_tag_field(idx, field);
                IF raw_value IS NOT NULL AND raw_value <> 'null'::jsonb THEN
                    -- encoding/json accepts only an integral int64 JSON token.
                    IF jsonb_typeof(raw_value) <> 'number' OR (raw_value#>>'{}') !~ '^-?[0-9]+$' THEN RETURN '{}'; END IF;
                END IF;
            END LOOP;
            start_byte := COALESCE((craftsky_tag_field(idx, 'byteStart')#>>'{}')::BIGINT, 0);
            end_byte := COALESCE((craftsky_tag_field(idx, 'byteEnd')#>>'{}')::BIGINT, 0);
        ELSE
            start_byte := -1;
            end_byte := 0;
        END IF;
        raw_features := craftsky_tag_field(facet, 'features');
        IF raw_features IS NULL OR raw_features = 'null'::jsonb THEN CONTINUE; END IF;
        IF jsonb_typeof(raw_features) <> 'array' THEN RETURN '{}'; END IF;
        FOR feature IN SELECT value FROM jsonb_array_elements(raw_features) LOOP
            IF feature = 'null'::jsonb THEN CONTINUE; END IF;
            IF jsonb_typeof(feature) <> 'object' THEN RETURN '{}'; END IF;
            raw_feature_type := craftsky_tag_field(feature, '$type');
            IF raw_feature_type IS NOT NULL AND raw_feature_type <> 'null'::jsonb
               AND jsonb_typeof(raw_feature_type) <> 'string' THEN RETURN '{}'; END IF;
            feature_type := raw_feature_type#>>'{}';
            field := CASE feature_type
                WHEN 'app.bsky.richtext.facet#tag' THEN 'tag'
                WHEN 'app.bsky.richtext.facet#mention' THEN 'did'
                WHEN 'app.bsky.richtext.facet#link' THEN 'uri'
                ELSE NULL END;
            IF field IS NULL THEN CONTINUE; END IF;
            raw_value := craftsky_tag_field(feature, field);
            IF raw_value IS NOT NULL AND raw_value <> 'null'::jsonb
               AND jsonb_typeof(raw_value) <> 'string' THEN RETURN '{}'; END IF;
            IF feature_type = 'app.bsky.richtext.facet#tag'
               AND start_byte >= 0 AND end_byte > start_byte
               AND end_byte <= octet_length(COALESCE(body, '')) THEN
                spelling := craftsky_tag_trim(raw_value#>>'{}');
                IF spelling IS NOT NULL AND spelling <> '' THEN result := array_append(result, spelling); END IF;
            END IF;
        END LOOP;
    END LOOP;
    RETURN result;
EXCEPTION WHEN numeric_value_out_of_range THEN
    RETURN '{}';
END;
$$;

CREATE FUNCTION craftsky_post_tag_spellings(record JSONB, is_project BOOLEAN) RETURNS TEXT[]
LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE AS $$
DECLARE
    common JSONB := craftsky_tag_field(craftsky_tag_field(record, 'project'), 'common');
    pattern JSONB := craftsky_tag_field(common, 'pattern');
    material JSONB;
    field TEXT;
    raw_tag JSONB;
    spelling TEXT;
    result TEXT[] := craftsky_facet_tag_spellings((craftsky_tag_field(record, 'text')#>>'{}'), craftsky_tag_field(record, 'facets'));
BEGIN
    IF is_project THEN
        IF jsonb_typeof(craftsky_tag_field(common, 'tags')) = 'array' THEN
            FOR raw_tag IN SELECT value FROM jsonb_array_elements(craftsky_tag_field(common, 'tags')) LOOP
                IF jsonb_typeof(raw_tag) = 'string' THEN
                    spelling := craftsky_tag_trim(raw_tag#>>'{}');
                    IF spelling <> '' THEN result := array_append(result, spelling); END IF;
                END IF;
            END LOOP;
        END IF;
        FOREACH field IN ARRAY ARRAY['name', 'designer', 'publisher'] LOOP
            result := result || craftsky_facet_tag_spellings((craftsky_tag_field(pattern, field)#>>'{}'), craftsky_tag_field(pattern, field || 'Facets'));
        END LOOP;
        IF jsonb_typeof(craftsky_tag_field(common, 'materials')) = 'array' THEN
            FOR material IN SELECT value FROM jsonb_array_elements(craftsky_tag_field(common, 'materials')) LOOP
                result := result || craftsky_facet_tag_spellings((craftsky_tag_field(material, 'text')#>>'{}'), craftsky_tag_field(material, 'facets'));
            END LOOP;
        END IF;
    END IF;
    RETURN ARRAY(SELECT DISTINCT tag COLLATE "C" FROM unnest(result) AS tag ORDER BY tag COLLATE "C");
END;
$$;

-- Adding a stored column derives historical spellings from retained public
-- records and keeps subsequent writes/replays consistent without a backfill job.
ALTER TABLE craftsky_posts ADD COLUMN tag_spellings TEXT[]
    GENERATED ALWAYS AS (craftsky_post_tag_spellings(record, is_project)) STORED;
