package app

import "social.craftsky/appview/internal/routes"

// RouteDependencies lowers process-wide composition into the narrow boundary
// owned by the HTTP routes package.
func RouteDependencies(deps *Deps) *routes.Dependencies {
	if deps == nil {
		return nil
	}
	return &routes.Dependencies{
		Config: routes.Config{
			Env:                       routes.Environment(deps.Config.Env),
			AllowedOrigins:            append([]string(nil), deps.Config.AllowedOrigins...),
			ExpectedHosts:             append([]string(nil), deps.Config.ExpectedHosts...),
			ExpectedHostAllowAnyPort:  deps.Config.ExpectedHostAllowAnyPort,
			DevRemoteAccess:           deps.Config.DevRemoteAccess,
			DevAuthSecret:             routes.Secret(deps.Config.DevAuthSecret.Reveal()),
			JSONBodyLimitBytes:        deps.Config.JSONBodyLimitBytes,
			MaxPostImages:             deps.Config.MaxPostImages,
			MaxImageUploadBytes:       deps.Config.MaxImageUploadBytes,
			ImageDecodeLimits:         deps.Config.ImageDecodeLimits,
			HTTPJSONBodyReadTimeout:   deps.Config.HTTPJSONBodyReadTimeout,
			HTTPUploadBodyReadTimeout: deps.Config.HTTPUploadBodyReadTimeout,
			InstagramLimits: routes.InstagramLimits{
				ChallengeDIDPer15Minutes:    deps.Config.InstagramLimits.ChallengeDIDPer15Minutes,
				ChallengeDevicePer15Minutes: deps.Config.InstagramLimits.ChallengeDevicePer15Minutes,
				ChallengeIPPer15Minutes:     deps.Config.InstagramLimits.ChallengeIPPer15Minutes,
				ConfirmationDIDPerHour:      deps.Config.InstagramLimits.ConfirmationDIDPerHour,
				ConfirmationDevicePerHour:   deps.Config.InstagramLimits.ConfirmationDevicePerHour,
				ImportsDIDPerHour:           deps.Config.InstagramLimits.ImportsDIDPerHour,
				ImportsDevicePerHour:        deps.Config.InstagramLimits.ImportsDevicePerHour,
			},
			InstagramTrustedProxyCIDRs:    deps.Config.InstagramDeployment.TrustedProxyCIDRs(),
			InstagramIntegrationAvailable: deps.Config.InstagramMeta.Enabled() && deps.Config.InstagramMeta.Configured(),
			EnableDevOAuthScheme:          deps.Config.EnableDevOAuthScheme,
			EnableDevModeration:           deps.Config.EnableDevModeration,
			DevModerationToken:            deps.Config.DevModerationToken,
			DevLabelerDID:                 deps.Config.DevLabelerDID,
			TrustedModerationSourceDIDs:   append([]string(nil), deps.Config.TrustedModerationSourceDIDs...),
		},
		Logger:                      deps.Logger,
		DB:                          deps.DB,
		AuthService:                 deps.AuthService,
		RateLimiter:                 deps.RateLimiter,
		Observability:               deps.Observability,
		AccountDeletion:             deps.AccountDeletion,
		AccountDeletionOAuth:        deps.AccountDeletionOAuth,
		AccountDeletionPendingLogin: deps.AccountDeletionPendingLogin,
		OAuthApp:                    deps.OAuthApp,
		OAuthArtifacts:              deps.OAuthArtifacts,
		OAuthFlow:                   deps.OAuthFlow,
		HandoffCoordinator:          deps.HandoffCoordinator,
		SessionLifecycle:            deps.SessionLifecycle,
		CraftskySessionStore:        deps.CraftskySessionStore,
		OwnerLifecycles:             deps.OwnerLifecycles,
		NewPendingPDSClient:         deps.NewPendingPDSClient,
		OnboardingProfile:           deps.OnboardingProfile,
		LoginCompleteURL:            deps.LoginCompleteURL,
		DeletionCompleteURL:         deps.DeletionCompleteURL,
		IdentityCacheUpdater:        deps.IdentityCacheUpdater,
		RepositoryTracker:           deps.RepositoryTracker,
		HandleResolver:              deps.HandleResolver,
		AuthoritativeHandleResolver: deps.AuthoritativeHandleResolver,
		Consumer:                    deps.Consumer,
		InstagramMembership:         deps.InstagramMembership,
		InstagramRateLimiter:        deps.InstagramRateLimiter,
		InstagramVerification:       deps.InstagramVerification,
		InstagramWebhook:            deps.InstagramWebhook,
		InstagramSuggestions:        deps.InstagramSuggestions,
		InstagramAccount:            deps.InstagramAccount,
		InstagramImports:            deps.InstagramImports,
		ProfileStore:                deps.ProfileStore,
		FollowerGrowth:              deps.FollowerGrowthStore,
		ProfileCustomisationStore:   deps.ProfileCustomisationStore,
		FollowStore:                 deps.FollowStore,
		RelationshipStore:           deps.RelationshipStore,
		RelationshipMutations:       deps.RelationshipMutations,
		ReportStore:                 deps.ReportStore,
		ReportForwarder:             deps.ReportForwarder,
		ModerationStore:             deps.ModerationStore,
		LanguagePreferences:         deps.LanguagePreferences,
		NewPDSEffects:               deps.NewPDSEffects,
		ScheduledPosts:              deps.ScheduledPosts,
		ScheduledMedia:              deps.ScheduledMedia,
		ScheduledManualPublisher:    deps.ScheduledManualPublisher,
	}
}
